/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PSim_PSim */

#ifndef _Included_PSim_PSim
#define _Included_PSim_PSim
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PSim_PSim
 * Method:    GetHandState
 * Signature: (Ljava/lang/String;LPSim/PostFlopState;)V
 */
JNIEXPORT void JNICALL Java_PSim_PSim_GetHandState__Ljava_lang_String_2LPSim_PostFlopState_2
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     PSim_PSim
 * Method:    RankHand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_PSim_PSim_RankHand__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     PSim_PSim
 * Method:    SimulateHand
 * Signature: (Ljava/lang/String;LPSim/SimResults;FFI)V
 */
JNIEXPORT void JNICALL Java_PSim_PSim_SimulateHand__Ljava_lang_String_2LPSim_SimResults_2FFI
  (JNIEnv *, jclass, jstring, jobject, jfloat, jfloat, jint);

/*
 * Class:     PSim_PSim
 * Method:    SimulateHandMulti
 * Signature: (Ljava/lang/String;LPSim/SimResults;III)V
 */
JNIEXPORT void JNICALL Java_PSim_PSim_SimulateHandMulti__Ljava_lang_String_2LPSim_SimResults_2III
  (JNIEnv *, jclass, jstring, jobject, jint, jint, jint);

/*
 * Class:     PSim_PSim
 * Method:    GetHandState
 * Signature: ([ILPSim/PostFlopState;)V
 */
JNIEXPORT void JNICALL Java_PSim_PSim_GetHandState___3ILPSim_PostFlopState_2
  (JNIEnv *, jclass, jintArray, jobject);

/*
 * Class:     PSim_PSim
 * Method:    RankHand
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_PSim_PSim_RankHand___3I
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     PSim_PSim
 * Method:    SimulateHand
 * Signature: ([ILPSim/SimResults;FFI)V
 */
JNIEXPORT void JNICALL Java_PSim_PSim_SimulateHand___3ILPSim_SimResults_2FFI
  (JNIEnv *, jclass, jintArray, jobject, jfloat, jfloat, jint);

/*
 * Class:     PSim_PSim
 * Method:    SimulateHandMulti
 * Signature: ([ILPSim/SimResults;III)V
 */
JNIEXPORT void JNICALL Java_PSim_PSim_SimulateHandMulti___3ILPSim_SimResults_2III
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint);

/*
 * Class:     PSim_PSim
 * Method:    GetHandStateBrief
 * Signature: (LPSim/PostFlopState;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PSim_PSim_GetHandStateBrief
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
