/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class handevaluator_jni_JNIHandEvaluator */

#ifndef _Included_handevaluator_jni_JNIHandEvaluator
#define _Included_handevaluator_jni_JNIHandEvaluator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     handevaluator_jni_JNIHandEvaluator
 * Method:    calculateClassIndex
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_handevaluator_jni_JNIHandEvaluator_calculateClassIndex
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     handevaluator_jni_JNIHandEvaluator
 * Method:    initializeJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_handevaluator_jni_JNIHandEvaluator_initializeJNI
  (JNIEnv *, jclass);

/*
 * Class:     handevaluator_jni_JNIHandEvaluator
 * Method:    runSuite
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_handevaluator_jni_JNIHandEvaluator_runSuite
  (JNIEnv *, jclass, jint);

/*
 * Class:     handevaluator_jni_JNIHandEvaluator
 * Method:    runOverhead
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_handevaluator_jni_JNIHandEvaluator_runOverhead
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
